"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/


#APP_NAME = os.environ.get("FLY_APP_NAME")
#ALLOWED_HOSTS = [f"{APP_NAME}.fly.dev"] 
#ALLOWED_HOSTS = [
#    f"{APP_NAME}.fly.dev",
#    "shoppingkarolito-black-sea-1752.fly.dev"
#]

ALLOWED_HOSTS = [
    
]
SECRET_KEY = config('SECRET_KEY', default='fallback-secret-key')

# SECURITY WARNING: keep the secret key used in production secrecont!

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = False
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cart',
    'payment',
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
  BASE_DIR / 'static/',
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Cambiado según supuesto servidor de La Salle
EMAIL_PORT = 587
EMAIL_HOST_USER = 'ittitoc@ulasalle.edu.pe'
EMAIL_HOST_PASSWORD = 'karina99'  # Cambiar a la contraseña real
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# la cookie de sesión de Django sea HttpOnly
SESSION_COOKIE_HTTPONLY = True

# Use a secure cookie for the session cookie if your site is entirely HTTPS.
SESSION_COOKIE_SECURE = True  # Only send cookie over HTTPS.

# Use a secure cookie for the CSRF cookie if your site is entirely HTTPS.
CSRF_COOKIE_SECURE = True  # Only send cookie over HTTPS.

# Set the CSRF cookie to be HttpOnly.
CSRF_COOKIE_HTTPONLY = True  # CSRF cookie not accessible via JavaScript.

CSRF_TRUSTED_ORIGINS = ['https://*.fly.dev']  # <-- Updated!
